baseURL = "https://thinklikecomputerscientist.github.io/"
languageCode = "en-us"
title = "Think like computer scientist"
paginate = 10
googleAnalytics = ""
disqusShortname = "hugo-minima"
theme = "minima"

[author]
name = "Tien Nguyen"
slogon = "Knowing is not enough, we must apply. Willing is not engough, we must do."
description = "Sharing is learning 😁"


[params]
# iam is the beginning words of your self-introduction.
iam = "I am"
# The subtitle will be shown after the title of your blog site
#  in a format like "title - subtitle".
subtitle = ""
# Comment decides the comment plugin used on your blog site, 
# available plugins: disqus, ovo.
comment = "disqus"
# timeformat 
timeformat = "Jan 2, 2006"
# switch for turning on/off lights.
switch = ["🌚", "🌝"]


# OvO is a comment plugin written by the author of Minima. 
# It is enabled when params.comment is set "ovo". You can
# find its documentation on https://github.com/ovojs/ovo.
# If you are using disqus, just ignore this field.
[params.ovo]
server = ""
placeholder = ""


# Params.social is an array containing your social network accounts,
# Each has a lowercase name, a svg formatted icon and a url to the 
# webpage of your account. They will be shown at the bottom of every
# page of your blog. 
# Be sure the svgs you select to use must have both the width and the
# height set 18. If you don't wanna put the svg code in this config
# file, you can instead save them to the `data/svg.toml` file under 
# the root directory of your blog using a format like `name = '<svg>'`
[[params.social]]
name = "github"  
url = "https://github.com/tiennvcs"
svg = ""
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tiennvuit"
svg = ""


# Menu.main is an array that's used to decide what entries can be shown
# on the navigator of yur blog. You can use a weight to make them ordered.
[[menu.main]]
name = "Home"
url = ["/home", "/"]
weight = 1
[[menu.main]]
name = "DSA"
url = "/categories"
weight = 2
[[menu.main]]
name = "Python"
url = "/python"
weight = 3
[[menu.main]]
name = "MA4ML"
url = "/ma4ml"
weight = 4
[[menu.main]]
name = "Machine Learning"
url = "/ml"
weight = 5
[[menu.main]]
name = "About"
url = "/about"
weight = 6


# You can classify your posts by setting taxanomies in the front matter like
# categories = ["apple", "banana"]
# series = ["s1", "s2"]
# tags = ["t1", "t2"]
# A little suggestion: one post belongs to one series, one category and multiple tags.
[taxonomies]
category = ["Data structure and algorithm", "Python", "Math for machine learning", "Machine learning",]
tag = ["Data structure and algorithm", "Python", "Math for machine learning", "Machine learning",]


# Make sure all the codes in a post are highlighted correctly
# so better not edit this.
[markup.highlight]
lineNos = true
noClasses = false